import type { FAQItem } from "../calculatorsData";

export const grossUpFaqs: FAQItem[] = [
  {
    "question": "What is a gross-up calculator and how does paycheck grossing up work?",
    "answer": "A gross-up calculator calculates the total gross pay required so that an employee receives an exact target net dollar amount after federal, state, local, and FICA payroll taxes are deducted. Grossing up is frequently used for employee bonuses, relocation stipends, and executive perks. Calculate exact gross amounts instantly using our free <a href=\"/calculators/gross-up\">Gross Up Calculator</a> and read our complete guide on <a href=\"/blog/gross-up-calculator-guide-payroll-bonus-tax-formula\">paycheck gross-up tax formulas</a>."
  },
  {
    "question": "How do you calculate annual gross income vs. net income?",
    "answer": "Annual gross income is your total earnings before any tax withholdings, retirement contributions, or health insurance deductions are subtracted. Net income (take-home pay) is the remaining cash deposited into your bank account after all deductions. To reverse-calculate gross salary from target net pay, use our <a href=\"/calculators/gross-up\">Reverse Tax & Gross-Up Calculator</a>."
  },
  {
    "question": "How much is a $60,000 annual salary per month after taxes?",
    "answer": "A $60,000 annual salary averages $5,000 per month gross. Depending on your state tax rate and filing status, effective tax withholdings (Federal Income Tax + FICA 7.65% + State Tax) total roughly 18% to 26%, resulting in a net monthly take-home pay of approximately $3,700 to $4,100 per month. Model your exact state tax breakdown with our <a href=\"/calculators/gross-up\">Paycheck Net Pay Estimator</a>."
  },
  {
    "question": "What is the difference between gross pay and net pay on a pay stub?",
    "answer": "Gross pay represents total wages earned during a pay period (hourly rate × hours worked, plus bonuses or overtime). Net pay is the final payment amount after subtracting pre-tax benefits (401k, HSA), mandatory payroll taxes (Social Security, Medicare), and income taxes. Estimate payroll taxes with our <a href=\"/calculators/gross-up\">Gross to Net Pay Calculator</a>."
  },
  {
    "question": "How does a reverse income tax or reverse tax calculator work?",
    "answer": "A reverse tax calculator uses the gross-up formula `Gross Pay = Target Net Amount ÷ (1 - Total Tax Percentage Rate)`. For example, to give an employee $1,000 net when combined tax withholdings equal 25%, the employer gross-up total is `$1,000 ÷ (1 - 0.25) = $1,333.33`. Try the reverse tax formula on our <a href=\"/calculators/gross-up\">Reverse Income Tax Calculator</a>."
  },
  {
    "question": "How to calculate payroll gross-up for bonuses and supplemental wages?",
    "answer": "The IRS taxes supplemental wages (bonuses, gifts, awards) at a flat 22% federal withholding rate plus 7.65% FICA (Social Security and Medicare) and applicable state tax. When grossing up a bonus, divide the desired net bonus by `(1 - Combined Supplemental Tax Rate)`. Calculate exact bonus payments using our <a href=\"/calculators/gross-up\">Bonus Gross-Up Calculator</a>."
  },
  {
    "question": "How do you find your year-to-date (YTD) gross pay from a pay stub or W-2?",
    "answer": "Your YTD gross pay is located on the earnings summary section of your pay stub, showing cumulative gross earnings from January 1st through the current pay period. On Form W-2, Box 1 reports taxable gross wages. Calculate YTD earnings projections with our <a href=\"/calculators/gross-up\">YTD Paycheck Estimator</a>."
  },
  {
    "question": "How do paycheck calculators like SurePayroll calculate state tax gross-ups in Texas or Pennsylvania?",
    "answer": "State tax gross-ups factor in specific state income tax rates. In states with zero state income tax (such as Texas, Florida, or Washington), gross-up calculations include only federal income tax (22% supplemental or marginal rate) and FICA (7.65%). In states like Pennsylvania (flat 3.07% tax) or California (progressive up to 13.3%), state rates are added to the combined denominator rate. Test state-specific rules with our <a href=\"/calculators/gross-up\">State Paycheck Gross-Up Estimator</a>."
  },
  {
    "question": "Why do employers gross up employee relocation and gift payments?",
    "answer": "Employers gross up relocation packages and non-cash executive rewards to ensure employees do not suffer an unexpected out-of-pocket tax penalty on employer-provided benefits. The gross-up covers the additional income tax liability generated by the perk. Model executive perk gross-ups with our free <a href=\"/calculators/gross-up\">Gross Up Calculator</a>."
  },
  {
    "question": "What is the formula for calculating net-to-gross pay?",
    "answer": "The net-to-gross formula is `Gross Pay = (Desired Net + Pre-Tax Fixed Deductions) ÷ (1 - Total Statutory Tax Rate)`. This accounts for both percentage-based taxes and fixed pre-tax deductions. Calculate net-to-gross values instantly using our interactive <a href=\"/calculators/gross-up\">Net to Gross Pay Calculator</a>."
  }
];
